INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (1, 1, 'Ufa');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (2, 1, 'Moscow');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (3, 1, 'Sochi');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (4, 1, 'Saint Petersburg');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (5, 1, 'Omsk');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (6, 1, 'Sevastopol');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (7, 1, 'Vladivostok');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (8, 1, 'Kazan');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (9, 2, 'New-York');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (10, 2, 'Washington');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (11, 2, 'Miami');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (12, 2, 'Los-Angeles');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (13, 2, 'Las-Vegas');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (14, 2, 'Detroit');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (15, 2, 'San Antonio');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (16, 2, 'Chicago');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (17, 3, 'Helsinki');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (18, 3, 'Nokia');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (19, 3, 'Oulu');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (20, 3, 'Vantaa');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (21, 3, 'Jyväskylä');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (22, 3, 'Espoo');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (23, 4, 'Paris');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (24, 4, 'Nice');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (25, 4, 'Marseille');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (26, 4, 'Lyon');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (27, 4, 'Strasbourg');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (28, 4, 'Rennes');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (29, 4, 'Bordeaux');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (30, 5, 'Berlin');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (31, 5, 'Hamburg');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (32, 5, 'Cologne');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (33, 5, 'Munich ');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (34, 5, 'Frankfurt am Main');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (35, 5, 'Düsseldorf');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (36, 5, ' Dortmund');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (37, 5, 'Leipzig');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (38, 5, 'Dresden');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (39, 5, 'Hanover');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (40, 6, 'Beijing');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (41, 6, 'Shanghai');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (42, 6, 'Wuhan');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (43, 7, 'Tokyo');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (44, 7, 'Nagoya');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (45, 7, 'Handa');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (46, 7, 'Toyota');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (47, 7, 'Kōchi');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (48, 7, 'Miyagi');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (49, 8, 'Rome');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (50, 8, 'Milan');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (51, 8, 'Naples');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (52, 8, 'Florence');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (53, 8, 'Genoa');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (54, 8, 'Palermo');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (55, 8, 'Turin');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (56, 10, 'Kyiv');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (57, 10, 'Kharkiv');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (58, 10, 'Odessa');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (59, 11, 'Minsk');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (60, 11, 'Salihorsk');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (61, 11, 'Grodno');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (70, 9, 'Barcelona');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (71, 9, 'Madrid');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (72, 9, 'Seville');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (73, 18, 'London');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (74, 18, 'Manchester ');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (75, 18, 'Liverpool ');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (76, 18, 'Newcastle ');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (83, 16, 'Sydney');
INSERT INTO travel_agency_db.city (id, country_id, city_name) VALUES (84, 16, 'Melbourne');